"""Pydantic schemas for Vision Service to FastAPI Event Ingestion Contract."""

from datetime import datetime
from enum import Enum
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field


class DirectionType(str, Enum):
    """Directional transit event types emitted by Vision Service."""
    ENTRY = "ENTRY"
    EXIT = "EXIT"
    UNRESOLVED = "UNRESOLVED"


class VisionEvidence(BaseModel):
    """Evidence metrics collected over the duration of a face tracklet."""
    model_config = ConfigDict(extra="forbid")

    peak_similarity: float = Field(
        ...,
        ge=-1.0,
        le=1.0,
        description="Highest cosine similarity observed within the track.",
    )
    mean_similarity: float = Field(
        ...,
        ge=-1.0,
        le=1.0,
        description="Average cosine similarity across supporting frames.",
    )
    supporting_frames: int = Field(
        ...,
        ge=0,
        description="Number of frames voting for the candidate identity.",
    )
    total_frames: int = Field(
        ...,
        ge=1,
        description="Total sampled frames where the track was observed.",
    )
    consistency_pct: float = Field(
        ...,
        ge=0.0,
        le=100.0,
        description="Percentage of track frames consistent with the top candidate.",
    )
    margin_over_runner_up: Optional[float] = Field(
        default=None,
        description="Score separation margin between candidate and second-best identity.",
    )
    runner_up_identity: Optional[str] = Field(
        default=None,
        description="Identity label of the closest competing gallery match.",
    )


class VisionEventCreate(BaseModel):
    """Standardized event payload transmitted by Vision Service to FastAPI."""
    model_config = ConfigDict(extra="forbid")

    event_id: str = Field(
        ...,
        min_length=1,
        description="Unique event UUID generated by vision service for idempotency.",
    )
    camera_id: str = Field(
        ...,
        min_length=1,
        description="Logical identifier for the camera and doorway.",
    )
    track_id: int = Field(
        ...,
        ge=0,
        description="ByteTrack sequential tracklet ID.",
    )
    identity: str = Field(
        ...,
        min_length=1,
        description="Biometric identity token/label (e.g. 'person_02', 'ST042', or 'UNKNOWN').",
    )
    direction: DirectionType = Field(
        ...,
        description="Movement event: ENTRY, EXIT, or UNRESOLVED.",
    )
    timestamp: datetime = Field(
        ...,
        description="ISO 8601 UTC timestamp of boundary crossing.",
    )
    evidence: VisionEvidence = Field(
        ...,
        description="Perception and tracking evidence metrics.",
    )


class VisionEventResponse(BaseModel):
    """Acknowledgement response returned to Vision Service upon ingestion."""
    event_id: str
    status: str = Field(
        ...,
        description="Ingestion status: e.g. 'accepted', 'duplicate', 'logged'.",
    )
    message: Optional[str] = Field(
        default=None,
        description="Optional human-readable confirmation message.",
    )
    processed_at: Optional[datetime] = Field(
        default=None,
        description="Timestamp when event was ingested.",
    )
